# Generated by Django 2.2 on 2020-03-22 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200322_2049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='locationDetail',
        ),
    ]
