# Generated by Django 2.2 on 2020-03-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200322_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Coronora Virus Positive'), (2, 'Shows Symptoms'), (3, 'Travel History Abroad'), (4, 'Close Contact'), (5, 'Normal User')], null=True),
        ),
    ]
