# Generated by Django 2.2 on 2020-03-25 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20200322_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdetail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_location', to=settings.AUTH_USER_MODEL),
        ),
    ]
